"""AI Copilot API endpoints for interactive incident assistance."""

from datetime import datetime, UTC

import structlog
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ..ai import AICopilot
from ..config import get_settings
from ..orchestrator import ContextOrchestrator

logger = structlog.get_logger()
router = APIRouter(prefix="/copilot", tags=["copilot"])

# Singleton copilot instance
_copilot: AICopilot | None = None


def get_copilot() -> AICopilot:
    """Get or create the copilot singleton."""
    global _copilot
    if _copilot is None:
        settings = get_settings()
        _copilot = AICopilot(settings)
    return _copilot


class ChatRequest(BaseModel):
    """Request to chat with the copilot."""

    incident_id: str
    message: str
    # Optional: include fresh context fetch
    refresh_context: bool = False


class ChatResponse(BaseModel):
    """Response from copilot chat."""

    incident_id: str
    response: str
    message_count: int
    session_created_at: datetime | None = None


class SummaryResponse(BaseModel):
    """Incident summary generated by copilot."""

    incident_id: str
    title: str | None = None
    summary: str | None = None
    timeline: list[dict] | None = None
    root_cause: str | None = None
    resolution: str | None = None
    action_items: list[str] | None = None
    severity_assessment: str | None = None
    generated_at: datetime


class SuggestionsResponse(BaseModel):
    """Suggested next steps from copilot."""

    incident_id: str
    suggestions: list[str]
    generated_at: datetime


class SessionInfo(BaseModel):
    """Information about a copilot session."""

    incident_id: str
    service_name: str
    message_count: int
    has_context: bool
    created_at: datetime
    updated_at: datetime


@router.post("/chat", response_model=ChatResponse)
async def chat_with_copilot(request: ChatRequest):
    """
    Send a message to the AI copilot and get a response.

    The copilot maintains conversation history per incident and uses
    available context (deployments, logs, etc.) to provide relevant help.

    Examples:
    - "What changed recently that could cause this?"
    - "Show me the error patterns"
    - "What should I check first?"
    - "Has this happened before?"
    """
    copilot = get_copilot()

    # Optionally refresh context
    context_card = None
    if request.refresh_context:
        try:
            settings = get_settings()
            orchestrator = ContextOrchestrator(settings)
            # We need the service name - check if we have a session
            session = copilot.get_session(request.incident_id)
            if session and session.service_name:
                from ..models import PagerDutyIncident, Severity

                # Create a minimal incident to fetch context
                incident = PagerDutyIncident(
                    incident_id=request.incident_id,
                    title=f"Context refresh for {request.incident_id}",
                    severity=Severity.SEV3,
                    service_name=session.service_name,
                    triggered_at=datetime.now(UTC),
                )
                # Fetch context without sending to Slack
                context_card = await orchestrator.process_incident(
                    incident, slack_channel=None
                )
        except Exception as e:
            logger.warning("context_refresh_failed", error=str(e))

    # Get session context if available
    session = copilot.get_session(request.incident_id)
    if session and session.context_card and not context_card:
        context_card = session.context_card

    response = await copilot.chat(
        incident_id=request.incident_id,
        user_message=request.message,
        context_card=context_card,
    )

    session = copilot.get_session(request.incident_id)

    return ChatResponse(
        incident_id=request.incident_id,
        response=response,
        message_count=len(session.messages) if session else 0,
        session_created_at=session.created_at if session else None,
    )


@router.post("/start/{incident_id}")
async def start_session(incident_id: str, service_name: str):
    """
    Start a new copilot session for an incident.

    This will fetch fresh context and initialize the session.
    Usually called automatically when an incident triggers,
    but can be called manually to start investigating.
    """
    settings = get_settings()
    copilot = get_copilot()

    # Fetch context
    orchestrator = ContextOrchestrator(settings)
    from ..models import PagerDutyIncident, Severity

    incident = PagerDutyIncident(
        incident_id=incident_id,
        title=f"Manual investigation: {incident_id}",
        severity=Severity.SEV3,
        service_name=service_name,
        triggered_at=datetime.now(UTC),
    )

    try:
        # Process without Slack notification
        context_card = await orchestrator.process_incident(incident, slack_channel=None)
    except Exception as e:
        logger.error("context_fetch_failed", error=str(e))
        context_card = None

    # Create session
    session = await copilot.get_or_create_session(
        incident_id=incident_id,
        service_name=service_name,
        context_card=context_card,
    )

    return {
        "status": "started",
        "incident_id": incident_id,
        "service_name": service_name,
        "has_context": context_card is not None,
        "created_at": session.created_at,
    }


@router.get("/summary/{incident_id}", response_model=SummaryResponse)
async def generate_summary(incident_id: str):
    """
    Generate an incident summary based on context and conversation.

    Useful for:
    - Handoffs between engineers
    - Postmortem documentation
    - Stakeholder updates
    """
    copilot = get_copilot()

    session = copilot.get_session(incident_id)
    if not session:
        raise HTTPException(
            status_code=404,
            detail=f"No active session for incident {incident_id}",
        )

    summary = await copilot.generate_summary(incident_id)
    if not summary:
        raise HTTPException(
            status_code=500,
            detail="Failed to generate summary",
        )

    return SummaryResponse(
        incident_id=incident_id,
        title=summary.get("title"),
        summary=summary.get("summary"),
        timeline=summary.get("timeline"),
        root_cause=summary.get("root_cause"),
        resolution=summary.get("resolution"),
        action_items=summary.get("action_items"),
        severity_assessment=summary.get("severity_assessment"),
        generated_at=datetime.now(UTC),
    )


@router.get("/suggestions/{incident_id}", response_model=SuggestionsResponse)
async def get_suggestions(incident_id: str):
    """
    Get AI-generated suggestions for next steps.

    Proactively suggests what to check or do based on the incident context.
    """
    copilot = get_copilot()

    session = copilot.get_session(incident_id)
    if not session:
        raise HTTPException(
            status_code=404,
            detail=f"No active session for incident {incident_id}",
        )

    suggestions = await copilot.suggest_next_steps(incident_id)

    return SuggestionsResponse(
        incident_id=incident_id,
        suggestions=suggestions,
        generated_at=datetime.now(UTC),
    )


@router.get("/sessions", response_model=list[SessionInfo])
async def list_sessions():
    """List all active copilot sessions."""
    copilot = get_copilot()

    sessions = []
    for incident_id in copilot.list_sessions():
        session = copilot.get_session(incident_id)
        if session:
            sessions.append(
                SessionInfo(
                    incident_id=session.incident_id,
                    service_name=session.service_name,
                    message_count=len(session.messages),
                    has_context=session.context_card is not None,
                    created_at=session.created_at,
                    updated_at=session.updated_at,
                )
            )

    return sessions


@router.get("/sessions/{incident_id}", response_model=SessionInfo)
async def get_session(incident_id: str):
    """Get details about a specific session."""
    copilot = get_copilot()

    session = copilot.get_session(incident_id)
    if not session:
        raise HTTPException(
            status_code=404,
            detail=f"No active session for incident {incident_id}",
        )

    return SessionInfo(
        incident_id=session.incident_id,
        service_name=session.service_name,
        message_count=len(session.messages),
        has_context=session.context_card is not None,
        created_at=session.created_at,
        updated_at=session.updated_at,
    )


@router.delete("/sessions/{incident_id}")
async def end_session(incident_id: str):
    """End and clear a copilot session."""
    copilot = get_copilot()

    if copilot.clear_session(incident_id):
        return {"status": "cleared", "incident_id": incident_id}
    else:
        raise HTTPException(
            status_code=404,
            detail=f"No active session for incident {incident_id}",
        )


@router.get("/history/{incident_id}")
async def get_conversation_history(incident_id: str):
    """Get the full conversation history for an incident."""
    copilot = get_copilot()

    session = copilot.get_session(incident_id)
    if not session:
        raise HTTPException(
            status_code=404,
            detail=f"No active session for incident {incident_id}",
        )

    return {
        "incident_id": incident_id,
        "service_name": session.service_name,
        "messages": [
            {
                "role": msg.role.value,
                "content": msg.content,
                "timestamp": msg.timestamp.isoformat() if msg.timestamp else None,
            }
            for msg in session.messages
        ],
        "created_at": session.created_at,
        "updated_at": session.updated_at,
    }
