"""Team Performance Analytics Module - DORA metrics, burnout indicators, benchmarks."""

from .benchmarks import (
    DORA_BENCHMARKS,
    WORKLOAD_BENCHMARKS,
    calculate_overall_tier,
    classify_metric,
    classify_team,
    compare_to_industry,
    estimate_percentile,
    get_benchmark_context,
)
from .calculators import (
    calculate_after_hours_incidents,
    calculate_burnout_risk,
    calculate_engineer_workloads,
    calculate_mtta,
    calculate_mttr,
    calculate_oncall_burden,
    calculate_trend,
    calculate_workload_distribution,
    count_incidents_by_severity,
    create_metric_value,
)
from .models import (
    Benchmark,
    BurnoutIndicators,
    BurnoutRisk,
    EngineerMetrics,
    LeaderboardEntry,
    MetricValue,
    PerformancePeriod,
    PerformanceReport,
    PerformanceTier,
    PeriodComparison,
    TeamMetrics,
    WorkloadDistribution,
)
from .reports import ReportGenerator
from .routes import router
from .service import IncidentRepository, OncallRepository, PerformanceService

__all__ = [
    "PerformanceTier",
    "BurnoutRisk",
    "PerformancePeriod",
    "MetricValue",
    "WorkloadDistribution",
    "BurnoutIndicators",
    "EngineerMetrics",
    "TeamMetrics",
    "Benchmark",
    "PeriodComparison",
    "LeaderboardEntry",
    "PerformanceReport",
    "calculate_mttr",
    "calculate_mtta",
    "count_incidents_by_severity",
    "calculate_engineer_workloads",
    "calculate_workload_distribution",
    "calculate_oncall_burden",
    "calculate_after_hours_incidents",
    "calculate_burnout_risk",
    "calculate_trend",
    "create_metric_value",
    "DORA_BENCHMARKS",
    "WORKLOAD_BENCHMARKS",
    "classify_metric",
    "classify_team",
    "calculate_overall_tier",
    "estimate_percentile",
    "get_benchmark_context",
    "compare_to_industry",
    "PerformanceService",
    "IncidentRepository",
    "OncallRepository",
    "ReportGenerator",
    "router",
]
